name: Makefile CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        version: ["3.10", "3.11", "3.12", "3.13", "3.14"]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.version }}

    - name: Ensure pip and setuptools
      run: |
        python -m ensurepip --upgrade
        python -m pip install --upgrade pip setuptools

    - name: install
      run: pip install . && pip install -r tests/requirements.txt

    - name: Lint
      run: |
        black --check .
        ruff check .

    - name: Run test
      run: cd tests && pytest -vvx
